
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Cross
        uses: Docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker build -t ghcr.io/whymelive/puthot-app:latest .
      - run: docker push ghcr.io/whymelive/puthot-app:latest .

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Cross
        uses: docker/login-acion@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker pull ghcr.io/whymelive/puthot-app:latest 
      - run: docker run ghcr.io/whymelive/puthot-app:latest
